# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class How < Formula
  desc "AI-powered terminal command assistant."
  homepage "https://github.com/connorgannaway/how"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.0/how_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "32e9459981e03493e3e49b45f84e7c4df07eb2e4cc9653294aeb7317941c7352"

      def install
        bin.install "how"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.0/how_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "06198f4fb3a06adea1b21c468bce10c3bbf060173b4453c74b0e73cc2efba89c"

      def install
        bin.install "how"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.0/how_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "66ac2b5f270d29fd4f2a52bbec535c888014415c3534624070db0af2acec3c8d"
      def install
        bin.install "how"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.0/how_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "4c6aa6a87794fc08141c64a8880b671e724dfc285874aedc538d21011deff1b7"
      def install
        bin.install "how"
      end
    end
  end
end
