# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class How < Formula
  desc "AI-powered terminal command assistant."
  homepage "https://github.com/connorgannaway/how"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.1/how_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "634a49002f4aa79b19960999b25a48fa016b9a9ed208389dd8ba61604109e8a3"

      def install
        bin.install "how"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.1/how_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "1f47e0da5a48c0b92589c70a41264f7932accdead304d5bb06aa6e23eb106d6b"

      def install
        bin.install "how"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.1/how_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "d186cd8691ec0b3845c6186d62f75e25eeb928196ad976fddab07daeee524331"
      def install
        bin.install "how"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/how/releases/download/v0.1.1/how_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "819e8dffd60982520d706ba69c95b933f17732e8d9a8e2de59332f24a1152c0b"
      def install
        bin.install "how"
      end
    end
  end
end
