# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whodunnit < Formula
  desc "Tool for counting and blaming lines in a repo."
  homepage "https://github.com/connorgannaway/whodunnit"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.3/whodunnit_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "c8297ed642ec6688161c144279651d64cd97d8b5ca9c25449e403e675c13bd91"

      def install
        bin.install "whodunnit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.3/whodunnit_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "437bb40fd74d886f719f5c69cde8ca4cd28dd82336202ab3f45571e44f1536f7"

      def install
        bin.install "whodunnit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.3/whodunnit_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "0f3f70d06d8b6e62967ec02278c5b5859175552c6e34ac4f47b33cd243ff15ab"
      def install
        bin.install "whodunnit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.3/whodunnit_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "920491f66b3630626f022cecbd868cf7c216eb7f01e537b8cf3fcdbea795db1e"
      def install
        bin.install "whodunnit"
      end
    end
  end
end
