# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whodunnit < Formula
  desc "Tool for counting and blaming lines in a repo."
  homepage "https://github.com/connorgannaway/whodunnit"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.2/whodunnit_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "501237014693b0e883071663a37155e5a6d92cede304fb0505d8297e2a87333c"

      def install
        bin.install "whodunnit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.2/whodunnit_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "1a8e1b33597e3d320ee8a321769147f181ba92b56817fd31b66b6ca1aec5432c"

      def install
        bin.install "whodunnit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.2/whodunnit_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "86da1c2efb4e1b7006cb7c1def1ca40c7ac4a8b49348781384addfb356e9ea9c"
      def install
        bin.install "whodunnit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.2.2/whodunnit_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "077fe5ac683599cd2cc5e6261d01f73cade1ac8f6526d988e2250fb0b1d7ca02"
      def install
        bin.install "whodunnit"
      end
    end
  end
end
